package demo.model;
// Generated 2018/2/24 �U�� 03:37:29 by Hibernate Tools 3.5.0.Final

/**
 * Members generated by hbm2java
 */
public class ContactUs implements java.io.Serializable {

	private int Cid;
	private String Cmail;
	private String Cname;
	private String CTel;
	private String Cmessage;
	
	
	public int getCid() {
		return Cid;
	}
	public String getCmail() {
		return Cmail;
	}
	public void setCmail(String cmail) {
		Cmail = cmail;
	}
	public void setCid(int cid) {
		Cid = cid;
	}
	public String getCname() {
		return Cname;
	}
	public void setCname(String cname) {
		Cname = cname;
	}
	public String getCTel() {
		return CTel;
	}
	public void setCTel(String cTel) {
		CTel = cTel;
	}
	public String getCmessage() {
		return Cmessage;
	}
	public void setCmessage(String cmessage) {
		Cmessage = cmessage;
	}
	
}
