package demo.model;
// Generated 2018/2/24 �U�� 03:37:29 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Members generated by hbm2java
 */
public class Members implements java.io.Serializable {

	private String mid;
	private String pwd;
	private String name;
	private Integer age;
	private String addr;
	private String tel;
	private String email;
	private boolean rating;

	private Set<Orders> orders = new HashSet<Orders>(0);
	public Members() {
	}

	public Set<Orders> getOrders() {
		return orders;
	}

	public void setOrders(Set<Orders> orders) {
		this.orders = orders;
	}

	public Members(String mid, String pwd, String name, boolean rating) {
		this.mid = mid;
		this.pwd = pwd;
		this.name = name;
		this.rating = rating;
	}

	public Members(String mid, String pwd, String name, Integer age, String addr, String tel, String email,
			boolean rating) {
		this.mid = mid;
		this.pwd = pwd;
		this.name = name;
		this.age = age;
		this.addr = addr;
		this.tel = tel;
		this.email = email;
		this.rating = rating;
	}

	public String getMid() {
		return this.mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isRating() {
		return this.rating;
	}

	public void setRating(boolean rating) {
		this.rating = rating;
	}

}
