package demo.model;
// Generated 2018/2/24 �U�� 03:37:29 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * Ordersdetail generated by hbm2java
 */
public class OrdersDetail implements java.io.Serializable {

	private Integer num;
	private String oid;
	private String name;
	private int qty;
	private BigDecimal price;
	
	private Orders orders;
	
	public Orders getOrders() {
		return orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public OrdersDetail() {
	}

	public OrdersDetail(String name, int qty, BigDecimal price) {
		this.name = name;
		this.qty = qty;
		this.price = price;
	}

	public OrdersDetail(String oid, String name, int qty, BigDecimal price) {
		this.oid = oid;
		this.name = name;
		this.qty = qty;
		this.price = price;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
