package demo.model;
// Generated 2018/2/24 �U�� 03:37:29 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private String pid;
	private String name;
	private String content;
	private int typeof;
	private BigDecimal price;
	private int instock;
	private Date indate;
	private int invalue;

	public Products() {
	}

	public Products(String pid, String name, String content, int typeof, BigDecimal price, int instock, Date indate,
			int invalue) {
		this.pid = pid;
		this.name = name;
		this.content = content;
		this.typeof = typeof;
		this.price = price;
		this.instock = instock;
		this.indate = indate;
		this.invalue = invalue;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public int getTypeof() {
		return this.typeof;
	}

	public void setTypeof(int typeof) {
		this.typeof = typeof;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public int getInstock() {
		return this.instock;
	}

	public void setInstock(int instock) {
		this.instock = instock;
	}

	public Date getIndate() {
		return this.indate;
	}

	public void setIndate(Date indate) {
		this.indate = indate;
	}

	public int getInvalue() {
		return this.invalue;
	}

	public void setInvalue(int invalue) {
		this.invalue = invalue;
	}

}
