package demo.model;
// Generated 2018/2/24 �U�� 03:37:29 by Hibernate Tools 3.5.0.Final

/**
 * Productsimage generated by hbm2java
 */
public class Productsimage implements java.io.Serializable {

	private Integer id;
	private String pid;
	private byte[] photo;

	public Productsimage() {
	}

	public Productsimage(String pid) {
		this.pid = pid;
	}

	public Productsimage(String pid, byte[] photo) {
		this.pid = pid;
		this.photo = photo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

}
