package demo.model;
// Generated 2018/2/24 �U�� 03:37:29 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Shopmasters generated by hbm2java
 */
public class Shopmasters implements java.io.Serializable {

	private String mid;
	private String pwd;
	private String name;
	private String email;
	private String sex;
	private boolean isTerminate;
	private boolean rating;
	private String modifyname;
	private Date modifyDate;

	public Shopmasters() {
	}

	public Shopmasters(String mid, String pwd, String name, String email, String sex, boolean isTerminate,
			boolean rating) {
		this.mid = mid;
		this.pwd = pwd;
		this.name = name;
		this.email = email;
		this.sex = sex;
		this.isTerminate = isTerminate;
		this.rating = rating;
	}

	public Shopmasters(String mid, String pwd, String name, String email, String sex, boolean isTerminate,
			boolean rating, String modifyname, Date modifyDate) {
		this.mid = mid;
		this.pwd = pwd;
		this.name = name;
		this.email = email;
		this.sex = sex;
		this.isTerminate = isTerminate;
		this.rating = rating;
		this.modifyname = modifyname;
		this.modifyDate = modifyDate;
	}

	public String getMid() {
		return this.mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public boolean isIsTerminate() {
		return this.isTerminate;
	}

	public void setIsTerminate(boolean isTerminate) {
		this.isTerminate = isTerminate;
	}

	public boolean isRating() {
		return this.rating;
	}

	public void setRating(boolean rating) {
		this.rating = rating;
	}

	public String getModifyname() {
		return this.modifyname;
	}

	public void setModifyname(String modifyname) {
		this.modifyname = modifyname;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
